# Generated by Django 3.2.2 on 2024-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MSAIM', 'MSAIM'), ('ComputerScience', 'ComputerScience'), ('InformationScience', 'InformationScience'), ('Electronics and Communication', 'Electronics and Communication'), ('Mechanical', 'Mechanical')], default='ComputerScience', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('Christ University Central Campus', 'Christ University Central Campus'), ('Christ University Kengeri Campus', 'Christ University Kengeri Campus')], max_length=50),
        ),
    ]
